# User specific configuration
#
# Copy this file to 'local.yml' (which is gitignored) and change as you like

# You can also create other setup files, e.g., 'myVM.yml'
# and specify it on the ansible-playbook command line:
# ansible-playbook ... playbook.yml -e @vars/myVM.yml

# Flag to rebuild everything from source even if it already exists
# epics_rebuild_all: true

# Modules to be built
m_base: false
m_p4p: false
m_areadetector: false
m_calc: false
m_sscan: false
  #m_busy: true
m_seq: false
m_stream: false

# Services & applications
phoebus: false
# oac-tree: true
archiver_appliance: false
channelfinder: true
# docker: true
# bluesky: true
